First running build after the update

diff --git a/packages/sysutils/busybox/scripts/init b/packages/sysutils/busybox/scripts/init
--- a/packages/sysutils/busybox/scripts/init
+++ b/packages/sysutils/busybox/scripts/init
@@ -1,167 +1,5 @@
 #!/bin/sh
 
-<<<<<<< HEAD
-################################################################################
-#      This file is part of OpenELEC - http://www.openelec.tv
-#      Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)
-#      Copyright (C) 2010-2011 Roman Weber (roman@openelec.tv)
-#      Copyright (C) 2012 Yann Cézard (eesprit@free.fr)
-#
-#  OpenELEC is free software: you can redistribute it and/or modify
-#  it under the terms of the GNU General Public License as published by
-#  the Free Software Foundation, either version 2 of the License, or
-#  (at your option) any later version.
-#
-#  OpenELEC is distributed in the hope that it will be useful,
-#  but WITHOUT ANY WARRANTY; without even the implied warranty of
-#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#  GNU General Public License for more details.
-#
-#  You should have received a copy of the GNU General Public License
-#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
-################################################################################
-
-  # create directories
-  /bin/busybox mkdir -p /dev
-  /bin/busybox mkdir -p /proc
-  /bin/busybox mkdir -p /sys
-  /bin/busybox mkdir -p /tmp
-  /bin/busybox mkdir -p /flash
-  /bin/busybox mkdir -p /sysroot
-  /bin/busybox mkdir -p /storage
-  /bin/busybox mkdir -p /hugepages
-
-  # mount all needed special filesystems
-  /bin/busybox mount -t devtmpfs devtmpfs /dev
-  /bin/busybox mount -t proc proc /proc
-  /bin/busybox mount -t sysfs sysfs /sys
-  /bin/busybox mount -t hugetlbfs hugetlbfs /hugepages
-
-  # common functions
-  . /functions
-
-  # set needed variables
-  MODULE_DIR=/lib/modules
-
-  UPDATE_ROOT=/storage/.update
-  UPDATE_DIR="$UPDATE_ROOT"
-
-  UPDATE_KERNEL="KERNEL"
-  UPDATE_SYSTEM="SYSTEM"
-  IMAGE_KERNEL="KERNEL"
-  IMAGE_SYSTEM="SYSTEM"
-
-  BOOT_STEP="start"
-  MD5_FAILED="0"
-  RUN_FSCK="yes"
-  RUN_FSCK_DISKS=""
-
-  NBD_DEVS="0"
-  FLASH_FREE_MIN="5"
-
-  INSTALLED_MEMORY=`cat /proc/meminfo | grep 'MemTotal:' | awk '{print $2}'`
-  SYSTEM_TORAM_LIMIT=1024000
-
-  LIVE="no"
-
-  # hide kernel log messages on console
-  echo '1 4 1 7' > /proc/sys/kernel/printk
-
-  # set ondemand up_threshold
-  if [ -e /sys/devices/system/cpu/cpufreq/ondemand/up_threshold ] ; then
-    echo 50 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
-  fi
-
-  # run platform_init script if exists
-  if [ -f "./platform_init" ]; then
-    ./platform_init
-  fi
-
-  # clear screen and hide cursor
-  clear
-  hidecursor
-
-  # parse command line arguments
-  for arg in $(cat /proc/cmdline); do
-    case $arg in
-      BOOT_IMAGE=*)
-        IMAGE_KERNEL="${arg#*=}"
-        ;;
-      SYSTEM_IMAGE=*)
-        IMAGE_SYSTEM="${arg#*=}"
-        ;;
-      boot=*)
-        boot="${arg#*=}"
-        case $boot in
-          ISCSI=*|NBD=*|NFS=*)
-            UPDATE_DISABLED=yes
-            FLASH_NETBOOT=yes
-            ;;
-          /dev/*|LABEL=*|UUID=*)
-            RUN_FSCK_DISKS="$RUN_FSCK_DISKS $boot"
-            ;;
-        esac
-        ;;
-      disk=*)
-        disk="${arg#*=}"
-        case $disk in
-          ISCSI=*|NBD=*|NFS=*)
-            STORAGE_NETBOOT=yes
-            ;;
-          /dev/*|LABEL=*|UUID=*)
-            RUN_FSCK_DISKS="$RUN_FSCK_DISKS $disk"
-            ;;
-        esac
-        ;;
-      wol_mac=*)
-        wol_mac="${arg#*=}"
-        ;;
-      wol_wait=*)
-        wol_wait="${arg#*=}"
-        ;;
-      textmode)
-        INIT_UNIT="--unit=textmode.target"
-        ;;
-      installer)
-        INIT_UNIT="--unit=installer.target"
-        ;;
-      debugging)
-        DEBUG=yes
-        ;;
-      progress)
-        PROGRESS=yes
-        INIT_ARGS="$INIT_ARGS --show-status=1"
-        ;;
-      nofsck)
-        RUN_FSCK=no
-        ;;
-      nosplash)
-        SPLASH=no
-        ;;
-      noram)
-        SYSTEM_TORAM=no
-        ;;
-      live)
-        LIVE=yes
-        ;;
-      overlay)
-        OVERLAY=yes
-        ;;
-      setfbres=*)
-        SWITCH_FRAMEBUFFER="${arg#*=}"
-        SWITCH_FRAMEBUFFER="${SWITCH_FRAMEBUFFER//,/ }"
-        ;;
-      break=*)
-        BREAK="${arg#*=}"
-        ;;
-    esac
-  done
-
-  if test "$DEBUG" = "yes"; then
-    exec 3>&1
-  else
-    exec 3>/dev/null
-=======
 # SPDX-License-Identifier: GPL-2.0-or-later
 # Copyright (C) 2010-2011 Roman Weber (roman@openelec.tv)
 # Copyright (C) 2012 Yann Cézard (eesprit@free.fr)
@@ -213,7 +51,7 @@ BREAK_TRIPPED="no"
 BIGFONT="1080"
 
 # Get a serial number if present (eg. RPi) otherwise use MAC address from eth0
-MACHINE_UID="$(awk '/^Serial/{s='0000000' $3; print substr(s, length(s) - 7)}' /proc/cpuinfo)"
+MACHINE_UID="$(cat /proc/cpuinfo | awk '/^Serial/{s=$3; gsub ("^0*","",s); print s}')"
 [ -z "$MACHINE_UID" ] && MACHINE_UID="$(cat /sys/class/net/eth0/address 2>/dev/null | tr -d :)"
 
 # common functions
@@ -223,7 +61,6 @@ MACHINE_UID="$(awk '/^Serial/{s='0000000' $3; print substr(s, length(s) - 7)}' /
 progress() {
   if test "$PROGRESS" = "yes"; then
     echo "### $1 ###" >&2
->>>>>>> 074a4508131af5e6e5a2dcdb1a78cc2789857ddc
   fi
 }
 
@@ -366,7 +203,7 @@ mount_nfs() {
 
   [ "$NFS_OPTIONS" = "$1" ] && NFS_OPTIONS=
 
-  mount_common "$NFS_EXPORT" "$2" "$3,nolock,rsize=32768,wsize=32768,$NFS_OPTIONS" "nfs"
+  mount_common "$NFS_EXPORT" "$2" "$3,nolock,soft,timeo=3,retrans=2,rsize=32768,wsize=32768,$NFS_OPTIONS" "nfs"
 }
 
 mount_ubifs() {
@@ -662,44 +499,24 @@ force_fsck() {
 check_disks() {
   if [ "$RUN_FSCK" = "yes" -a -n "$RUN_FSCK_DISKS" ]; then
     progress "Checking disk(s): $RUN_FSCK_DISKS"
-    echo "Checking disk(s): $RUN_FSCK_DISKS" >/dev/kmsg
-    for i in 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0; do
-      /usr/sbin/fsck -T -M -p -a $RUN_FSCK_DISKS >/dev/fsck.latest 2>&1
-      FSCK_RET=$?
-      cat /dev/fsck.latest >>/dev/fsck.log
+    /usr/sbin/fsck -T -M -p -a $RUN_FSCK_DISKS > /dev/null 2>&1
+    FSCK_RET=$?
 
-      # FSCK_RET is the bit-wise OR of the exit codes for each filesystem that is checked.
-      if [ $FSCK_RET -ge 16 ]; then
-        progress "General error, continuing..."
-        break
-      elif [ $(( $FSCK_RET & 8 )) -eq 8 ]; then
-        # device not found
-        if [ $i -eq 0 ]; then
-          progress "Device not found, continuing..."
-        else
-          usleep 500000
-        fi
-      elif [ $(( $FSCK_RET & 4 )) -eq 4 ]; then
-        # errors left
-        force_fsck
-      elif [ $(( $FSCK_RET & 2 )) -eq 2 ]; then
-        # reboot needed
-        echo "Filesystem repaired, reboot needed..."
-        do_reboot
-      elif [ $(( $FSCK_RET & 1 )) -eq 1 ]; then
-        # filesystem errors corrected
-        progress "Filesystem errors corrected , continuing..."
-        break
-      elif [ $FSCK_RET -eq 0 ]; then
-        # no errors found
-        progress "No filesystem errors found, continuing..."
-        break
-      fi
-    done
-    while read line; do
-      [ -n "$line" ] && echo "fsck: ${line::160}" >/dev/kmsg
-    done </dev/fsck.latest
-    rm -f /dev/fsck.latest
+    # FSCK_RET is the bit-wise OR of the exit codes for each filesystem that is checked.
+    if [ $(( $FSCK_RET & 4 )) -eq 4 ]; then
+      # errors left
+      force_fsck
+    elif [ $(( $FSCK_RET & 2 )) -eq 2 ]; then
+      # reboot needed
+      echo "Filesystem repaired, reboot needed..."
+      do_reboot
+    elif [ $(( $FSCK_RET & 1 )) -eq 1 ]; then
+      # filesystem errors corrected
+      progress "Filesystem errors corrected , continuing..."
+    elif [ $(( $FSCK_RET & 0 )) -eq 0 ]; then
+      # no errors found
+      progress "No filesystem errors found, continuing..."
+    fi
   fi
 }
 
@@ -739,13 +556,10 @@ mount_flash() {
 cleanup_flash() {
   progress "Cleaning up flash (if required)"
 
-  if [ -f /flash/pieeprom.bin -o -f /flash/pieeprom.upd -o -f /flash/vl805.bin ]; then
+  if [ -f /flash/pieeprom.upd ]; then
     mount -o remount,rw /flash
-
-    rm -f /flash/pieeprom.bin /flash/pieeprom.upd /flash/pieeprom.sig
-    rm -f /flash/vl805.bin /flash/vl805.sig
+    rm -f /flash/pieeprom.bin /flash/pieeprom.upd
     rm -f /flash/recovery.bin /flash/recovery.[0-9][0-9][0-9] /flash/RECOVERY.[0-9][0-9][0-9]
-
     mount -o remount,ro /flash
   fi
 }
@@ -844,10 +658,6 @@ check_out_of_space() {
 
 do_cleanup() {
   StartProgress spinner "Cleaning up... "
-
-  if mountpoint -q /update; then
-    umount /update
-  fi
 
   if [ -d $UPDATE_ROOT/.tmp/mnt ]; then
     if mountpoint -q $UPDATE_ROOT/.tmp/mnt ; then
@@ -1110,6 +920,7 @@ check_update() {
   umount /sysroot
   update_file "System" "$UPDATE_SYSTEM" "/flash/$IMAGE_SYSTEM"
   update_bootloader
+  umount /update
   do_cleanup
   do_reboot
 }
@@ -1245,9 +1056,6 @@ for arg in $(cat /proc/cmdline); do
     bigfont=*)
       BIGFONT="${arg#*=}"
       ;;
-    ip=*)
-      KERNEL_IPCONFIG="yes"
-      ;;
   esac
 done
 
@@ -1314,10 +1122,6 @@ fi
 
 if [ "$FLASH_NETBOOT" = "yes" ]; then
   echo "" > /sysroot/dev/.flash_netboot
-fi
-
-if [ "$KERNEL_IPCONFIG" = "yes" ]; then
-  echo "" > /sysroot/dev/.kernel_ipconfig
 fi
 
 # swap can not be used over nfs.(see scripts/mount-swap)
